{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "insider-case.fullname" . }}
  labels:
    {{- include "insider-case.labels" . | nindent 4 }}
    release: monitoring   # kube-prometheus-stack'in default selector'ı
spec:
  selector:
    matchLabels:
      {{- include "insider-case.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}